/* palette_count.h — GENERATED by gen_tables.py.  Do not edit.
 *
 * Number of colour schemes in palette.bin / jd_palette[].  Each scheme is
 * 32768 ARGB entries == 131072 bytes, so
 *     sizeof(palette.bin) == JD_SCHEMES * 131072.
 *
 * bridge.c should use this instead of a literal.  draw.s is assembled as
 * .s (no C preprocessor) so gen_tables.py rewrites its scheme-modulus
 * literal in place; both therefore track this number automatically.
 */
#ifndef JD_PALETTE_COUNT_H
#define JD_PALETTE_COUNT_H

#define JD_SCHEMES 120

/* scheme index -> source : name
 *     0  house  jewels
 *     1  house  ember
 *     2  house  royal
 *     3  house  gilded
 *     4  house  ice
 *     5  house  spring
 *     6  ref    resurrect-64
 *     7  ref    endesga-32
 *     8  ref    apollo
 *     9  ref    lospec500
 *    10  ref    endesga-64
 *    11  ref    cc-29
 *    12  ref    slso8
 *    13  ref    pear36
 *    14  ref    aap-64
 *    15  ref    31
 *    16  ref    sweetie-16
 *    17  ref    pico-8
 *    18  ref    vinik24
 *    19  ref    fantasy-24
 *    20  ref    journey
 *    21  ref    nintendo-entertainment-system
 *    22  ref    lost-century
 *    23  ref    zughy-32
 *    24  ref    mulfok32
 *    25  ref    na16
 *    26  ref    wplace-palette-free-colours
 *    27  ref    steam-lords
 *    28  ref    nyx8
 *    29  ref    blk-nx64
 *    30  lab    chasm
 *    31  lab    funkyfuture-8
 *    32  lab    technogarten
 *    33  lab    cyberpunk-neons
 *    34  lab    sunraze
 *    35  lab    fireball-32
 *    36  lab    bubblegum-16
 *    37  lab    pop-rox
 *    38  lab    vaporsthetic
 *    39  lab    berry-nebula
 *    40  lab    azure-abyss
 *    41  lab    unstable
 *    42  lab    wlk44-v2
 *    43  lab    ink-crimson
 *    44  lab    holographic-mode
 *    45  lab    cathedral_glass
 *    46  lab    peacock_court
 *    47  lab    aurora_veil
 *    48  lab    macaw_riot
 *    49  lab    koi_pond_dusk
 *    50  lab    blacklight_lounge
 *    51  lab    byzantine_mosaic
 *    52  lab    holi_burst
 *    53  lab    obsidian_magma
 *    54  lab    orchid_greenhouse
 *    55  lab    thunderhead
 *    56  lab    carnival_glass
 *    57  lab    absinthe_hour
 *    58  lab    nebula_reef
 *    59  lab    spice_bazaar
 *    60  lab    cobalt_vigil
 *    61  lab    oxblood_chapel
 *    62  lab    tide_and_coral
 *    63  lab    orchid_and_absinthe
 *    64  lab    foundry_blue
 *    65  lab    fen_water
 *    66  lab    ripening_field
 *    67  lab    nightbloom
 *    68  lab    cardinal_and_jade
 *    69  lab    harvest_storm
 *    70  lab    acid_rail
 *    71  lab    blood_ultraviolet
 *    72  lab    sugared_almond
 *    73  lab    sea_glass_morning
 *    74  lab    hammered_copper
 *    75  lab    newsprint_siren
 *    76  lab    blueprint_cut
 *    77  lab    kiln_and_clay
 *    78  lab    moss_and_stone
 *    79  lab    carnival_at_midnight
 *    80  lab    wormwood
 *    81  lab    orchid_vault
 *    82  lab    frost_signal
 *    83  lab    sodium_and_slate
 *    84  lab    riso_indigo
 *    85  lab    iris_morning
 *    86  lab    harbour_dusk
 *    87  lab    verdigris_alarm
 *    88  lab    flare_path
 *    89  lab    serpentine
 *    90  lab    neon_alley
 *    91  lab    violet_reactor
 *    92  lab    antique_bronze
 *    93  lab    pewter_rose
 *    94  lab    cobalt_steel
 *    95  lab    gold_rule
 *    96  lab    magenta_press
 *    97  lab    sea_fog
 *    98  lab    lichen_and_slate
 *    99  lab    heather_moor
 *   100  lab    jade_lantern
 *   101  lab    damson_hour
 *   102  lab    brass_vigil
 *   103  lab    violet_and_wheat
 *   104  lab    fuchsia_and_verdigris
 *   105  lab    claret_run
 *   106  lab    reed_bed
 *   107  lab    lagoon_triad
 *   108  lab    marsh_light
 *   109  lab    sodium_rose
 *   110  lab    ion_trail
 *   111  lab    lilac_powder
 *   112  lab    buttermilk_field
 *   113  lab    periwinkle_hour
 *   114  lab    rose_gold
 *   115  lab    verdigris_steel
 *   116  lab    hazard_tape
 *   117  lab    ultraviolet_press
 *   118  lab    driftwood_and_slate
 *   119  lab    mushroom_and_mauve
 */

#endif /* JD_PALETTE_COUNT_H */
