/* auto-generated by tools/gen_registry.sh */
#include "../jellydazzle.h"
extern void pattern_001(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_002(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_003(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_004(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_005(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_006(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_007(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_008(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_009(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_010(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_011(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_012(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_013(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_014(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_015(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_016(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_017(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_018(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_019(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_020(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_021(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_022(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_023(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_024(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_025(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_026(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_027(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_028(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_029(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_030(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_031(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_032(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_033(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_034(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_035(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_036(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_037(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_038(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_039(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_040(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_041(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_042(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_043(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_044(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_045(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_046(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_047(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_048(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_049(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_050(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_051(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_052(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_053(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_054(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_055(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_056(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_057(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_058(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_059(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_060(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_061(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_062(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_063(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_064(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_065(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_066(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_067(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_068(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_069(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_070(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_071(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_072(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_073(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_074(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_075(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_076(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_077(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_078(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_079(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_080(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_081(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_082(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_083(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_084(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_085(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_086(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_087(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_088(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_089(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_090(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_091(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_092(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_093(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_094(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_095(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_096(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_097(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_098(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_099(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_100(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_101(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_102(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_103(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_104(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_105(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_106(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_107(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_108(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_109(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_110(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_111(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_112(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_113(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_114(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_115(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_116(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_117(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_118(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_119(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_120(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_121(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_122(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_123(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_124(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_125(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_126(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_127(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_128(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_129(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_130(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_131(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_132(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_133(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_134(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_135(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_136(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_137(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_138(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_139(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_140(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_141(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_142(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_143(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_144(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_145(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_146(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_147(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_148(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_149(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_150(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_151(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_152(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_153(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_154(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_155(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_156(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_157(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_158(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_159(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_160(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_161(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_162(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_163(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_164(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_165(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_166(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_167(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_168(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_169(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_170(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_171(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_172(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_173(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_174(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_175(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_176(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_177(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_178(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_179(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_180(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_181(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_182(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_183(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_184(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_185(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_186(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_187(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_188(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_189(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_190(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_191(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_192(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_193(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_194(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_195(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_196(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_197(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_198(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_199(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_200(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_201(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
const jd_pattern_fn jd_patterns[] = {
    pattern_001,
    pattern_002,
    pattern_003,
    pattern_004,
    pattern_005,
    pattern_006,
    pattern_007,
    pattern_008,
    pattern_009,
    pattern_010,
    pattern_011,
    pattern_012,
    pattern_013,
    pattern_014,
    pattern_015,
    pattern_016,
    pattern_017,
    pattern_018,
    pattern_019,
    pattern_020,
    pattern_021,
    pattern_022,
    pattern_023,
    pattern_024,
    pattern_025,
    pattern_026,
    pattern_027,
    pattern_028,
    pattern_029,
    pattern_030,
    pattern_031,
    pattern_032,
    pattern_033,
    pattern_034,
    pattern_035,
    pattern_036,
    pattern_037,
    pattern_038,
    pattern_039,
    pattern_040,
    pattern_041,
    pattern_042,
    pattern_043,
    pattern_044,
    pattern_045,
    pattern_046,
    pattern_047,
    pattern_048,
    pattern_049,
    pattern_050,
    pattern_051,
    pattern_052,
    pattern_053,
    pattern_054,
    pattern_055,
    pattern_056,
    pattern_057,
    pattern_058,
    pattern_059,
    pattern_060,
    pattern_061,
    pattern_062,
    pattern_063,
    pattern_064,
    pattern_065,
    pattern_066,
    pattern_067,
    pattern_068,
    pattern_069,
    pattern_070,
    pattern_071,
    pattern_072,
    pattern_073,
    pattern_074,
    pattern_075,
    pattern_076,
    pattern_077,
    pattern_078,
    pattern_079,
    pattern_080,
    pattern_081,
    pattern_082,
    pattern_083,
    pattern_084,
    pattern_085,
    pattern_086,
    pattern_087,
    pattern_088,
    pattern_089,
    pattern_090,
    pattern_091,
    pattern_092,
    pattern_093,
    pattern_094,
    pattern_095,
    pattern_096,
    pattern_097,
    pattern_098,
    pattern_099,
    pattern_100,
    pattern_101,
    pattern_102,
    pattern_103,
    pattern_104,
    pattern_105,
    pattern_106,
    pattern_107,
    pattern_108,
    pattern_109,
    pattern_110,
    pattern_111,
    pattern_112,
    pattern_113,
    pattern_114,
    pattern_115,
    pattern_116,
    pattern_117,
    pattern_118,
    pattern_119,
    pattern_120,
    pattern_121,
    pattern_122,
    pattern_123,
    pattern_124,
    pattern_125,
    pattern_126,
    pattern_127,
    pattern_128,
    pattern_129,
    pattern_130,
    pattern_131,
    pattern_132,
    pattern_133,
    pattern_134,
    pattern_135,
    pattern_136,
    pattern_137,
    pattern_138,
    pattern_139,
    pattern_140,
    pattern_141,
    pattern_142,
    pattern_143,
    pattern_144,
    pattern_145,
    pattern_146,
    pattern_147,
    pattern_148,
    pattern_149,
    pattern_150,
    pattern_151,
    pattern_152,
    pattern_153,
    pattern_154,
    pattern_155,
    pattern_156,
    pattern_157,
    pattern_158,
    pattern_159,
    pattern_160,
    pattern_161,
    pattern_162,
    pattern_163,
    pattern_164,
    pattern_165,
    pattern_166,
    pattern_167,
    pattern_168,
    pattern_169,
    pattern_170,
    pattern_171,
    pattern_172,
    pattern_173,
    pattern_174,
    pattern_175,
    pattern_176,
    pattern_177,
    pattern_178,
    pattern_179,
    pattern_180,
    pattern_181,
    pattern_182,
    pattern_183,
    pattern_184,
    pattern_185,
    pattern_186,
    pattern_187,
    pattern_188,
    pattern_189,
    pattern_190,
    pattern_191,
    pattern_192,
    pattern_193,
    pattern_194,
    pattern_195,
    pattern_196,
    pattern_197,
    pattern_198,
    pattern_199,
    pattern_200,
    pattern_201,
};
const int jd_pattern_count = 201;
