/* auto-generated by tools/gen_registry.sh */
#include "../jellydazzle.h"
extern void pattern_001(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_002(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_003(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_004(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_005(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_006(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_007(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_008(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_009(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_010(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_011(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_012(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_013(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_014(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_015(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_016(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_017(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_018(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_019(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_020(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_021(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_022(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_023(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_024(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_025(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_026(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_027(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_028(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_029(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_030(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_031(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_032(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_033(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_034(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_035(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_036(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_037(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_038(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_039(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_040(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_041(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_042(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_043(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_044(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_045(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_046(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_047(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_048(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_049(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_050(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_051(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_052(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_053(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_054(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_055(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_056(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_057(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_058(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_059(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_060(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_061(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_062(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_063(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_064(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_065(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_066(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_067(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_068(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_069(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_070(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_071(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_072(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_073(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_074(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_075(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_076(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_077(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_078(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_079(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_080(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_081(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_082(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_083(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_084(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_085(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_086(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_087(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_088(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_089(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_090(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_091(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_092(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_093(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_094(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_095(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_096(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_097(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_098(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_099(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_100(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
const jd_pattern_fn jd_patterns[] = {
    pattern_001,
    pattern_002,
    pattern_003,
    pattern_004,
    pattern_005,
    pattern_006,
    pattern_007,
    pattern_008,
    pattern_009,
    pattern_010,
    pattern_011,
    pattern_012,
    pattern_013,
    pattern_014,
    pattern_015,
    pattern_016,
    pattern_017,
    pattern_018,
    pattern_019,
    pattern_020,
    pattern_021,
    pattern_022,
    pattern_023,
    pattern_024,
    pattern_025,
    pattern_026,
    pattern_027,
    pattern_028,
    pattern_029,
    pattern_030,
    pattern_031,
    pattern_032,
    pattern_033,
    pattern_034,
    pattern_035,
    pattern_036,
    pattern_037,
    pattern_038,
    pattern_039,
    pattern_040,
    pattern_041,
    pattern_042,
    pattern_043,
    pattern_044,
    pattern_045,
    pattern_046,
    pattern_047,
    pattern_048,
    pattern_049,
    pattern_050,
    pattern_051,
    pattern_052,
    pattern_053,
    pattern_054,
    pattern_055,
    pattern_056,
    pattern_057,
    pattern_058,
    pattern_059,
    pattern_060,
    pattern_061,
    pattern_062,
    pattern_063,
    pattern_064,
    pattern_065,
    pattern_066,
    pattern_067,
    pattern_068,
    pattern_069,
    pattern_070,
    pattern_071,
    pattern_072,
    pattern_073,
    pattern_074,
    pattern_075,
    pattern_076,
    pattern_077,
    pattern_078,
    pattern_079,
    pattern_080,
    pattern_081,
    pattern_082,
    pattern_083,
    pattern_084,
    pattern_085,
    pattern_086,
    pattern_087,
    pattern_088,
    pattern_089,
    pattern_090,
    pattern_091,
    pattern_092,
    pattern_093,
    pattern_094,
    pattern_095,
    pattern_096,
    pattern_097,
    pattern_098,
    pattern_099,
    pattern_100,
};
const int jd_pattern_count = 100;
