/* JellyDazzle pattern plug-in contract.
 * A pattern paints fb (w*h ARGB u32, row-major). frame = global frame
 * counter; sl = segment-local frame 0..2047 (~34s @60fps) — accumulator
 * patterns clear their canvas when sl==0 and build until segment end;
 * repaint patterns ignore sl. seed = per-segment random (stable within
 * the segment). pal = 32768-entry ARGB palette, already scheme-blended
 * and crossfading slowly — index it with (anything & 0x7FFF).
 * Motion law: SLOW and SMOOTH. Nothing may strobe. */
#include <stdint.h>
#define JD_PAL_MASK 0x7FFF
/* ---- JellyDazzleAudio ------------------------------------------------
 * What the machine can hear, smoothed so visuals sway instead of strobe.
 * All fields 0..1024. Read them; never write them. When there is no
 * microphone (or silence) everything decays to 0 and `live` is 0, and the
 * engine falls back to its own clocks exactly as before. */
typedef struct {
    uint16_t level;      /* overall loudness                     */
    uint16_t bass;       /* ~86-260 Hz   — kick, bassline        */
    uint16_t mid;        /* ~350-2k Hz   — voice, body           */
    uint16_t treble;     /* 2k-22k Hz    — cymbals, air          */
    uint16_t beat;       /* 1024 on an onset, decays over ~0.2 s */
    uint16_t bpm_q8;     /* tempo estimate, Q8; 0 = unsure       */
    uint16_t live;       /* 1 while sound is actually arriving   */
} jd_audio;

extern jd_audio g_audio;
int  jd_audio_init(void);    /* 1 = listening, 0 = no input device */
void jd_audio_tick(void);    /* call once per frame, before drawing */
void jd_audio_close(void);

typedef void (*jd_pattern_fn)(uint32_t *fb, int w, int h,
                              int frame, int sl, uint32_t seed,
                              const uint32_t *pal);

/* Registry, generated by tools/gen_registry.sh. The names exist so the app can
 * tell you what is on screen right now (ABOUT card, key A) rather than making
 * you guess from a screenshot. */
extern const jd_pattern_fn jd_patterns[];
extern const char *const jd_pattern_names[];
extern const unsigned char jd_pattern_family[];
extern const int jd_pattern_count;

/* what the compositor is showing, for the ABOUT readout */
typedef struct { int routine; int role; int live; } jd_nowplaying;
int jd_now_playing(jd_nowplaying *out, int max);   /* returns count filled */
const char *jd_routine_name(int rt);
const uint32_t *jd_blend_ramp(void);   /* shared ramp, read-only (gate) */

/* LIVE CONTROL (3.0) — raised by the keyboard, consumed by the compositor.
 * C asks for a different colour set, S for a different set of shapes. */
extern int jd_req_palette;
extern int jd_req_shape;

/* ---- CONTRAST TAP (3.0.4, measurement only) --------------------------
 * A hook into the composite, for tools/gate_harness.c `contrast`.  NULL in
 * every shipping run, so a normal frame pays three predictable branches.
 *
 * Why a tap rather than two runs of the engine: the compositor ADAPTS to
 * measured frame cost (g_ewma_ms, g_mood, g_hot), so two runs of the same
 * start frame diverge and a with/without-overlays diff across runs measures
 * the divergence, not the accent.  Within ONE frame the composite is a pure
 * function of that frame's layer buffers, so the counterfactual "what was
 * under the accent" is exact and free.
 *
 *   stage = JD_TAP_GROUND    fb holds the ground composite, no overlays yet;
 *                            slot is the incumbent ground slot.
 *   stage = JD_TAP_OVERLAY   fb holds the composite with overlay `slot` just
 *                            blended on top; routine/w_now/blend describe it.
 *   stage = JD_TAP_FINAL     fb is the delivered frame: boot ramp, dead-air
 *                            gain, audio bloom, emblem and HUD all applied.
 * The callback must not write fb. */
enum { JD_TAP_GROUND = 0, JD_TAP_OVERLAY, JD_TAP_FINAL };
extern void (*jd_tap)(int stage, int slot, int routine, int w_now, int blend,
                      const uint32_t *fb, int w, int h);
