/* auto-generated by tools/gen_registry.sh — do not edit */
#include "../engine/jellydazzle.h"
extern void pattern_001(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_002(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_003(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_004(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_005(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_006(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_007(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_008(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_009(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_010(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_011(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_012(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_013(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_014(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_015(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_016(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_017(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_018(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_019(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_020(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_021(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_022(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_023(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_024(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_025(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_026(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_027(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_028(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_029(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_030(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_031(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_032(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_033(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_034(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_035(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_036(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_037(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_038(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_039(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_040(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_041(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_042(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_043(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_044(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_045(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_046(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_047(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_048(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_049(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_050(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_051(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_052(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_053(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_054(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_055(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_056(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_057(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_058(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_059(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_060(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_061(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_062(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_063(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_064(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_065(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_066(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_067(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_068(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_069(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_070(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_071(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_072(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_073(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_074(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_075(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_076(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_077(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_078(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_079(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_080(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_081(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_082(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_083(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_084(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_085(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_086(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_087(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_088(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_089(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_090(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_091(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_092(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_093(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_094(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_095(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_096(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_097(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_098(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_099(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_100(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_101(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_102(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_103(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_104(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_105(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_106(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_107(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_108(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_109(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_110(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_111(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_112(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_113(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_114(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_115(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_116(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_117(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_118(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_119(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_120(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_121(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_122(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_123(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_124(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_125(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_126(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_127(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_128(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_129(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_130(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_131(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_132(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_133(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_134(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_135(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_136(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_137(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_138(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_139(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_140(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_141(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_142(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_143(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_144(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_145(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_146(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_147(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_148(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_149(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_150(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_151(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_152(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_153(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_154(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_155(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_156(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_157(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_158(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_159(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_160(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_161(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_162(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_163(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_164(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_165(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_166(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_167(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_168(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_169(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_170(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_171(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_172(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_173(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_174(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_175(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_176(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_177(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_178(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_179(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_180(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_181(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_182(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_183(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_184(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_185(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_186(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_187(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_188(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_189(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_190(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_191(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_192(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_193(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_194(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_195(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_196(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_197(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_198(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_199(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_200(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_201(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_202(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_203(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_204(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_205(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_206(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_207(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_208(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_209(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_210(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_211(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_212(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_213(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_214(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_215(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_216(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_217(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_218(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_219(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_220(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_221(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_222(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_223(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_224(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_225(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_226(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_227(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_228(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_229(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_230(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_231(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_232(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_233(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_234(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_235(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_236(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_237(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_238(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_239(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_240(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_241(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_242(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_243(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_244(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_245(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_246(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_247(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_248(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_249(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_250(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_251(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_252(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_253(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_254(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_255(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_256(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_257(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_258(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_259(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_260(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_261(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_262(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_263(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_264(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_265(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_266(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_267(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_268(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_269(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_270(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_271(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_272(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_273(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_274(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_275(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_276(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_277(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_278(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_279(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_280(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_281(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_282(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_283(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_284(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_285(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_286(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_287(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_288(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_289(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_290(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_291(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_292(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_293(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_294(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_295(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_296(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_297(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_298(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_299(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_300(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_301(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_302(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_303(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_304(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_305(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_306(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_307(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_308(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_309(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_310(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_311(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_312(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_313(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_314(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_315(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_316(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_317(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_318(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_319(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_320(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_321(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_322(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_323(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_324(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_325(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_326(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_327(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_328(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_329(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_330(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_331(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_332(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_333(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_334(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_335(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_336(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_337(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_338(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_339(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_340(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_341(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_342(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_343(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_344(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_345(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_346(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_347(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_348(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_349(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_350(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_351(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_352(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_353(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_354(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_355(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_356(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_357(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_358(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_359(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_360(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_361(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_362(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_363(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_364(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_365(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_366(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_367(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_368(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_369(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_370(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_371(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_372(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_373(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_374(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_375(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_376(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_377(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_378(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_379(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_380(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_381(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_382(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_383(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_384(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_385(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_386(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_387(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_388(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_389(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_390(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_391(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_392(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_393(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_394(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_395(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_396(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_397(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_398(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_399(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_400(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_401(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_402(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_403(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_404(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_405(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_406(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_407(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_408(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_409(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_410(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_411(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_412(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_413(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_414(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_415(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_416(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_417(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_418(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_419(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_420(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_421(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_422(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_423(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_424(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_425(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_426(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_427(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_428(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_429(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_430(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_431(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_432(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_433(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_434(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_435(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_436(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_437(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_438(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_439(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_440(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_441(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_442(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_443(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_444(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_445(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_446(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_447(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_448(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_449(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_450(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_451(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_452(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_453(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_454(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_455(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_456(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_457(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_458(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_459(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_460(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_461(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_462(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_463(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_464(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_465(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_466(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_467(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_468(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_469(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_470(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_471(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_472(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_473(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_474(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_475(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_476(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_477(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_478(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_479(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_480(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_481(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_482(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_483(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_484(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_485(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_486(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_487(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_488(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_489(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_490(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_491(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_492(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_493(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_494(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_495(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_496(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_497(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_498(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_499(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_500(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_501(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_502(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_503(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_504(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_505(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_506(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_507(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_508(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_509(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_510(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_511(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_512(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_513(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_514(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_515(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_516(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_517(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_518(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_519(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_520(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_521(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_522(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_523(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_524(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_525(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_526(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_527(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_528(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_529(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_530(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_531(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_532(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_533(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_534(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_535(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_536(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_537(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_538(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_539(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_540(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_541(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_542(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_543(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_544(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_545(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_546(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_547(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_548(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_549(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_550(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_551(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_552(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_553(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_554(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_555(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_556(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_557(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_558(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_559(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_560(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_561(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_562(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_563(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_564(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_565(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_566(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_567(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_568(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_569(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_570(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_571(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_572(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_573(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_574(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_575(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_576(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_577(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_578(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_579(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_580(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_581(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_582(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_583(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_584(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_585(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_586(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_587(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_588(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_589(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_590(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_591(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_592(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_593(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_594(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_595(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_596(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_597(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_598(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_599(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_600(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_601(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_602(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_603(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_604(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_605(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_606(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_607(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_608(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_609(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
extern void pattern_610(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);
const jd_pattern_fn jd_patterns[] = {
    pattern_001,
    pattern_002,
    pattern_003,
    pattern_004,
    pattern_005,
    pattern_006,
    pattern_007,
    pattern_008,
    pattern_009,
    pattern_010,
    pattern_011,
    pattern_012,
    pattern_013,
    pattern_014,
    pattern_015,
    pattern_016,
    pattern_017,
    pattern_018,
    pattern_019,
    pattern_020,
    pattern_021,
    pattern_022,
    pattern_023,
    pattern_024,
    pattern_025,
    pattern_026,
    pattern_027,
    pattern_028,
    pattern_029,
    pattern_030,
    pattern_031,
    pattern_032,
    pattern_033,
    pattern_034,
    pattern_035,
    pattern_036,
    pattern_037,
    pattern_038,
    pattern_039,
    pattern_040,
    pattern_041,
    pattern_042,
    pattern_043,
    pattern_044,
    pattern_045,
    pattern_046,
    pattern_047,
    pattern_048,
    pattern_049,
    pattern_050,
    pattern_051,
    pattern_052,
    pattern_053,
    pattern_054,
    pattern_055,
    pattern_056,
    pattern_057,
    pattern_058,
    pattern_059,
    pattern_060,
    pattern_061,
    pattern_062,
    pattern_063,
    pattern_064,
    pattern_065,
    pattern_066,
    pattern_067,
    pattern_068,
    pattern_069,
    pattern_070,
    pattern_071,
    pattern_072,
    pattern_073,
    pattern_074,
    pattern_075,
    pattern_076,
    pattern_077,
    pattern_078,
    pattern_079,
    pattern_080,
    pattern_081,
    pattern_082,
    pattern_083,
    pattern_084,
    pattern_085,
    pattern_086,
    pattern_087,
    pattern_088,
    pattern_089,
    pattern_090,
    pattern_091,
    pattern_092,
    pattern_093,
    pattern_094,
    pattern_095,
    pattern_096,
    pattern_097,
    pattern_098,
    pattern_099,
    pattern_100,
    pattern_101,
    pattern_102,
    pattern_103,
    pattern_104,
    pattern_105,
    pattern_106,
    pattern_107,
    pattern_108,
    pattern_109,
    pattern_110,
    pattern_111,
    pattern_112,
    pattern_113,
    pattern_114,
    pattern_115,
    pattern_116,
    pattern_117,
    pattern_118,
    pattern_119,
    pattern_120,
    pattern_121,
    pattern_122,
    pattern_123,
    pattern_124,
    pattern_125,
    pattern_126,
    pattern_127,
    pattern_128,
    pattern_129,
    pattern_130,
    pattern_131,
    pattern_132,
    pattern_133,
    pattern_134,
    pattern_135,
    pattern_136,
    pattern_137,
    pattern_138,
    pattern_139,
    pattern_140,
    pattern_141,
    pattern_142,
    pattern_143,
    pattern_144,
    pattern_145,
    pattern_146,
    pattern_147,
    pattern_148,
    pattern_149,
    pattern_150,
    pattern_151,
    pattern_152,
    pattern_153,
    pattern_154,
    pattern_155,
    pattern_156,
    pattern_157,
    pattern_158,
    pattern_159,
    pattern_160,
    pattern_161,
    pattern_162,
    pattern_163,
    pattern_164,
    pattern_165,
    pattern_166,
    pattern_167,
    pattern_168,
    pattern_169,
    pattern_170,
    pattern_171,
    pattern_172,
    pattern_173,
    pattern_174,
    pattern_175,
    pattern_176,
    pattern_177,
    pattern_178,
    pattern_179,
    pattern_180,
    pattern_181,
    pattern_182,
    pattern_183,
    pattern_184,
    pattern_185,
    pattern_186,
    pattern_187,
    pattern_188,
    pattern_189,
    pattern_190,
    pattern_191,
    pattern_192,
    pattern_193,
    pattern_194,
    pattern_195,
    pattern_196,
    pattern_197,
    pattern_198,
    pattern_199,
    pattern_200,
    pattern_201,
    pattern_202,
    pattern_203,
    pattern_204,
    pattern_205,
    pattern_206,
    pattern_207,
    pattern_208,
    pattern_209,
    pattern_210,
    pattern_211,
    pattern_212,
    pattern_213,
    pattern_214,
    pattern_215,
    pattern_216,
    pattern_217,
    pattern_218,
    pattern_219,
    pattern_220,
    pattern_221,
    pattern_222,
    pattern_223,
    pattern_224,
    pattern_225,
    pattern_226,
    pattern_227,
    pattern_228,
    pattern_229,
    pattern_230,
    pattern_231,
    pattern_232,
    pattern_233,
    pattern_234,
    pattern_235,
    pattern_236,
    pattern_237,
    pattern_238,
    pattern_239,
    pattern_240,
    pattern_241,
    pattern_242,
    pattern_243,
    pattern_244,
    pattern_245,
    pattern_246,
    pattern_247,
    pattern_248,
    pattern_249,
    pattern_250,
    pattern_251,
    pattern_252,
    pattern_253,
    pattern_254,
    pattern_255,
    pattern_256,
    pattern_257,
    pattern_258,
    pattern_259,
    pattern_260,
    pattern_261,
    pattern_262,
    pattern_263,
    pattern_264,
    pattern_265,
    pattern_266,
    pattern_267,
    pattern_268,
    pattern_269,
    pattern_270,
    pattern_271,
    pattern_272,
    pattern_273,
    pattern_274,
    pattern_275,
    pattern_276,
    pattern_277,
    pattern_278,
    pattern_279,
    pattern_280,
    pattern_281,
    pattern_282,
    pattern_283,
    pattern_284,
    pattern_285,
    pattern_286,
    pattern_287,
    pattern_288,
    pattern_289,
    pattern_290,
    pattern_291,
    pattern_292,
    pattern_293,
    pattern_294,
    pattern_295,
    pattern_296,
    pattern_297,
    pattern_298,
    pattern_299,
    pattern_300,
    pattern_301,
    pattern_302,
    pattern_303,
    pattern_304,
    pattern_305,
    pattern_306,
    pattern_307,
    pattern_308,
    pattern_309,
    pattern_310,
    pattern_311,
    pattern_312,
    pattern_313,
    pattern_314,
    pattern_315,
    pattern_316,
    pattern_317,
    pattern_318,
    pattern_319,
    pattern_320,
    pattern_321,
    pattern_322,
    pattern_323,
    pattern_324,
    pattern_325,
    pattern_326,
    pattern_327,
    pattern_328,
    pattern_329,
    pattern_330,
    pattern_331,
    pattern_332,
    pattern_333,
    pattern_334,
    pattern_335,
    pattern_336,
    pattern_337,
    pattern_338,
    pattern_339,
    pattern_340,
    pattern_341,
    pattern_342,
    pattern_343,
    pattern_344,
    pattern_345,
    pattern_346,
    pattern_347,
    pattern_348,
    pattern_349,
    pattern_350,
    pattern_351,
    pattern_352,
    pattern_353,
    pattern_354,
    pattern_355,
    pattern_356,
    pattern_357,
    pattern_358,
    pattern_359,
    pattern_360,
    pattern_361,
    pattern_362,
    pattern_363,
    pattern_364,
    pattern_365,
    pattern_366,
    pattern_367,
    pattern_368,
    pattern_369,
    pattern_370,
    pattern_371,
    pattern_372,
    pattern_373,
    pattern_374,
    pattern_375,
    pattern_376,
    pattern_377,
    pattern_378,
    pattern_379,
    pattern_380,
    pattern_381,
    pattern_382,
    pattern_383,
    pattern_384,
    pattern_385,
    pattern_386,
    pattern_387,
    pattern_388,
    pattern_389,
    pattern_390,
    pattern_391,
    pattern_392,
    pattern_393,
    pattern_394,
    pattern_395,
    pattern_396,
    pattern_397,
    pattern_398,
    pattern_399,
    pattern_400,
    pattern_401,
    pattern_402,
    pattern_403,
    pattern_404,
    pattern_405,
    pattern_406,
    pattern_407,
    pattern_408,
    pattern_409,
    pattern_410,
    pattern_411,
    pattern_412,
    pattern_413,
    pattern_414,
    pattern_415,
    pattern_416,
    pattern_417,
    pattern_418,
    pattern_419,
    pattern_420,
    pattern_421,
    pattern_422,
    pattern_423,
    pattern_424,
    pattern_425,
    pattern_426,
    pattern_427,
    pattern_428,
    pattern_429,
    pattern_430,
    pattern_431,
    pattern_432,
    pattern_433,
    pattern_434,
    pattern_435,
    pattern_436,
    pattern_437,
    pattern_438,
    pattern_439,
    pattern_440,
    pattern_441,
    pattern_442,
    pattern_443,
    pattern_444,
    pattern_445,
    pattern_446,
    pattern_447,
    pattern_448,
    pattern_449,
    pattern_450,
    pattern_451,
    pattern_452,
    pattern_453,
    pattern_454,
    pattern_455,
    pattern_456,
    pattern_457,
    pattern_458,
    pattern_459,
    pattern_460,
    pattern_461,
    pattern_462,
    pattern_463,
    pattern_464,
    pattern_465,
    pattern_466,
    pattern_467,
    pattern_468,
    pattern_469,
    pattern_470,
    pattern_471,
    pattern_472,
    pattern_473,
    pattern_474,
    pattern_475,
    pattern_476,
    pattern_477,
    pattern_478,
    pattern_479,
    pattern_480,
    pattern_481,
    pattern_482,
    pattern_483,
    pattern_484,
    pattern_485,
    pattern_486,
    pattern_487,
    pattern_488,
    pattern_489,
    pattern_490,
    pattern_491,
    pattern_492,
    pattern_493,
    pattern_494,
    pattern_495,
    pattern_496,
    pattern_497,
    pattern_498,
    pattern_499,
    pattern_500,
    pattern_501,
    pattern_502,
    pattern_503,
    pattern_504,
    pattern_505,
    pattern_506,
    pattern_507,
    pattern_508,
    pattern_509,
    pattern_510,
    pattern_511,
    pattern_512,
    pattern_513,
    pattern_514,
    pattern_515,
    pattern_516,
    pattern_517,
    pattern_518,
    pattern_519,
    pattern_520,
    pattern_521,
    pattern_522,
    pattern_523,
    pattern_524,
    pattern_525,
    pattern_526,
    pattern_527,
    pattern_528,
    pattern_529,
    pattern_530,
    pattern_531,
    pattern_532,
    pattern_533,
    pattern_534,
    pattern_535,
    pattern_536,
    pattern_537,
    pattern_538,
    pattern_539,
    pattern_540,
    pattern_541,
    pattern_542,
    pattern_543,
    pattern_544,
    pattern_545,
    pattern_546,
    pattern_547,
    pattern_548,
    pattern_549,
    pattern_550,
    pattern_551,
    pattern_552,
    pattern_553,
    pattern_554,
    pattern_555,
    pattern_556,
    pattern_557,
    pattern_558,
    pattern_559,
    pattern_560,
    pattern_561,
    pattern_562,
    pattern_563,
    pattern_564,
    pattern_565,
    pattern_566,
    pattern_567,
    pattern_568,
    pattern_569,
    pattern_570,
    pattern_571,
    pattern_572,
    pattern_573,
    pattern_574,
    pattern_575,
    pattern_576,
    pattern_577,
    pattern_578,
    pattern_579,
    pattern_580,
    pattern_581,
    pattern_582,
    pattern_583,
    pattern_584,
    pattern_585,
    pattern_586,
    pattern_587,
    pattern_588,
    pattern_589,
    pattern_590,
    pattern_591,
    pattern_592,
    pattern_593,
    pattern_594,
    pattern_595,
    pattern_596,
    pattern_597,
    pattern_598,
    pattern_599,
    pattern_600,
    pattern_601,
    pattern_602,
    pattern_603,
    pattern_604,
    pattern_605,
    pattern_606,
    pattern_607,
    pattern_608,
    pattern_609,
    pattern_610,
};
const char *const jd_pattern_names[] = {
    "001 kaleido rose",
    "002 p4m quilt",
    "003 hex snowfold",
    "004 mirror truchet",
    "005 breathing fold",
    "006 tri morph",
    "007 pinwheel spiral",
    "008 octa mandala",
    "009 lissa web",
    "010 mosaic quilt",
    "011 plasma mandala",
    "012 rotozoom kaleido",
    "013 tunnel bloom",
    "014 copper octarings",
    "015 twister star",
    "016 shadebob rosette",
    "017 metaball kiss",
    "018 kefrens spiral",
    "019 moire silk",
    "020 feedback fractal",
    "021 ripple duet",
    "022 xor rings",
    "023 silk gratings",
    "024 munch frost",
    "025 ember triad",
    "026 spoke moire",
    "027 wedge ripples",
    "028 quasicrystal",
    "029 tartan beat",
    "030 octa facets",
    "031 spirograph bloom",
    "032 harmonograph veil",
    "033 rose engine",
    "034 lissajous weave",
    "035 string cardioid",
    "036 epicycle lace",
    "037 pendulum web",
    "038 guilloche rings",
    "039 butterfly lace",
    "040 maurer rose",
    "041 cyclic bloom",
    "042 bz pinwheel",
    "043 turing labyrinth",
    "044 majority quilt",
    "045 lenia bloom",
    "046 rps trichrome",
    "047 target choir",
    "048 excitable spirals",
    "049 voronoi breath",
    "050 turing spots",
    "051 firework garden",
    "052 orbit weave",
    "053 gravity rose",
    "054 starfield warp",
    "055 comet carousel",
    "056 ribbon swarm",
    "057 galaxy pinwheel",
    "058 fountain arcs",
    "059 binary dance",
    "060 meteor veil",
    "061 checker tunnel",
    "062 twist corridor",
    "063 spiral zoom",
    "064 starburst forge",
    "065 echo mandala",
    "066 hex tunnel",
    "067 twin tunnels",
    "068 wormhole pond",
    "069 pillar hall",
    "070 vortex petals",
    "071 silk currents",
    "072 vine waltz",
    "073 frost court",
    "074 slow lightning",
    "075 coral lace",
    "076 kelp cathedral",
    "077 mycelium veil",
    "078 turing garden",
    "079 golden bloom",
    "080 tendril rose",
    "081 poly morph",
    "082 greek key",
    "083 patch quilt",
    "084 gear rosettes",
    "085 vector machine",
    "086 gem orbit",
    "087 chevron court",
    "088 star cross",
    "089 oval drums",
    "090 diamond burst",
    "091 diamond confetti",
    "092 greek key panel",
    "093 cathedral fan",
    "094 thread web",
    "095 ring machine",
    "096 scanline butterfly",
    "097 magenta fireworks",
    "098 gear flower quad",
    "099 racetrack drums",
    "100 pinwheel swirl",
    "101 physarum veil",
    "102 vortex silk",
    "103 dragon unfold",
    "104 ice ray lattice",
    "105 rule mandala",
    "106 medusa drift",
    "107 stereographic cage",
    "108 vega bulge",
    "109 rain pond",
    "110 firefly sync",
    "111 physarum veins",
    "112 vortex ink",
    "113 sandpile mandala",
    "114 khatim weave",
    "115 vega bulge",
    "116 hilbert unfold",
    "117 cloth lattice",
    "118 harmonic lantern",
    "119 rose window",
    "120 rule loom",
    "121 chladni sand",
    "122 caustic net",
    "123 apollonian",
    "124 poincare web",
    "125 attractor dust",
    "126 orbit lace",
    "127 dipole filings",
    "128 aggregate bloom",
    "129 torus knot",
    "130 pentagrid",
    "131 times table",
    "132 tesseract drift",
    "133 doyle coil",
    "134 aurora curtain",
    "135 kelvin wake",
    "136 dipole lines",
    "137 rutt etra relief",
    "138 soap bubbles",
    "139 harmonic orb",
    "140 newton filigree",
    "141 chladni sand",
    "142 attractor smoke",
    "143 caustic pool",
    "144 newton filigree",
    "145 aurora curtains",
    "146 apollonian rings",
    "147 tesseract drift",
    "148 pendulum wave",
    "149 bubble iris",
    "150 relief lantern",
    "151 chladni filaments",
    "152 pentagrid lattice",
    "153 loxodrome drift",
    "154 hyperbolic court",
    "155 knot loom",
    "156 apollonian tide",
    "157 supershape bloom",
    "158 blaze",
    "159 caustic veil",
    "160 chrome relief",
    "161 curve loom",
    "162 orbital lobes",
    "163 droste spiral",
    "164 kolam loom",
    "165 vortex street",
    "166 star trails",
    "167 medusa drift",
    "168 schotter drift",
    "169 braid loom",
    "170 gyroid veil",
    "171 physarum veil",
    "172 villarceau weave",
    "173 steiner necklace",
    "174 braid loom",
    "175 glenz vectors",
    "176 bob rosette",
    "177 sandpile mandala",
    "178 doyle spiral",
    "179 harmonic lantern",
    "180 hilbert weave",
    "181 icosahedral mirror",
    "182 glass weave",
    "183 string hyperboloid",
    "184 caustic billiard",
    "185 sandpile",
    "186 marbling",
    "187 harmonic lantern",
    "188 plait loom",
    "189 reiter crystal",
    "190 glenz vectors",
    "191 hopf weave",
    "192 steiner pearls",
    "193 cord braid",
    "194 harmonic shell",
    "195 aperture star",
    "196 craquelure",
    "197 fern dust",
    "198 whirl nest",
    "199 talbot carpet",
    "200 lorenz ribbon",
    "201 lava lamp",
    "202 silk veil",
    "203 aurora curtain",
    "204 woven field",
    "205 lattice windows",
    "206 breathing membrane",
    "207 ribbed drape",
    "208 moire gauze",
    "209 smoke field",
    "210 oil slick",
    "211 marble veins",
    "212 cell tissue",
    "213 plume feathers",
    "214 jelly bells",
    "215 coral fan",
    "216 frost ferns",
    "217 dune field",
    "218 kelp forest",
    "219 lace doily",
    "220 honeycomb breath",
    "221 basket weave",
    "222 ripple pond",
    "223 caustic net",
    "224 fish scales",
    "225 peacock eyes",
    "226 spiral galaxy",
    "227 wind grass",
    "228 rope net",
    "229 stained glass",
    "230 nebula wisps",
    "231 tide foam",
    "232 zebra flow",
    "233 crinkled foil",
    "234 wave terraces",
    "235 petal rosette",
    "236 tartan veil",
    "237 dew web",
    "238 vortex sheet",
    "239 fungal gills",
    "240 mesh warp",
    "241 river delta",
    "242 quilted puff",
    "243 leopard rosettes",
    "244 kite tiles",
    "245 orbit rings",
    "246 sinew strands",
    "247 pearl curtain",
    "248 kagome weave",
    "249 canyon strata",
    "250 chain mail",
    "251 star lattice",
    "252 fog banks",
    "253 vine trellis",
    "254 pinwheel ribs",
    "255 lotus layers",
    "256 wing veins",
    "257 lichen patches",
    "258 crystal facets",
    "259 chevron stream",
    "260 bubble foam",
    "261 gauze layers",
    "262 loom threads",
    "263 pine needles",
    "264 root veins",
    "265 medallion grid",
    "266 sun dapples",
    "267 dragon scales",
    "268 ice shards",
    "269 velvet folds",
    "270 tapestry bands",
    "271 aurora swirl",
    "272 hex bokeh",
    "273 ribbon streams",
    "274 moire kaleido",
    "275 smoke rings",
    "276 marble kaleido",
    "277 aurora sheet",
    "278 vault ribs",
    "279 cell kaleido",
    "280 barchan dunes",
    "281 feather mandala",
    "282 comb jelly",
    "283 coral polyps",
    "284 frost edges",
    "285 dune perspective",
    "286 mirror veil",
    "287 checker breath",
    "288 phyllotaxis",
    "289 sea anemone",
    "290 origami folds",
    "291 moss carpet",
    "292 op waves",
    "293 lantern rows",
    "294 wisteria",
    "295 meander key",
    "296 truchet ribbons",
    "297 quasi penrose",
    "298 corner rays",
    "299 worm tubes",
    "300 eyelet lace",
    "301 impact web",
    "302 cirrus streaks",
    "303 sand dollars",
    "304 twill weave",
    "305 moire circles",
    "306 paisley field",
    "307 lily pads",
    "308 brain coral",
    "309 smoke columns",
    "310 oil rings",
    "311 agate slices",
    "312 membrane web",
    "313 plume spiral",
    "314 tentacle curtain",
    "315 coral mandala",
    "316 frost star",
    "317 dune sea",
    "318 silk twist",
    "319 lattice bloom",
    "320 membrane pores",
    "321 ring tunnel",
    "322 quasi twelve",
    "323 brush strokes",
    "324 braid ropes",
    "325 moth wing",
    "326 spirograph veil",
    "327 prism bars",
    "328 rose window",
    "329 fern wall",
    "330 wisp curls",
    "331 mosaic wave",
    "332 starburst field",
    "333 tulle gather",
    "334 sponge pores",
    "335 aurora dome",
    "336 slow plasma",
    "337 plasma bloom",
    "338 warped plasma",
    "339 plasma lozenge",
    "340 polar plasma",
    "341 nested sines",
    "342 soft checker plasma",
    "343 orbiting blobs",
    "344 silk bands",
    "345 tri plasma",
    "346 deep plasma",
    "347 curl plasma",
    "348 dawn clouds",
    "349 aurora sheets",
    "350 fog banks",
    "351 rain veil",
    "352 sunset bands",
    "353 storm front",
    "354 rolling mist",
    "355 heat shimmer",
    "356 overcast lozenges",
    "357 twilight glow",
    "358 nebula veils",
    "359 star cloud",
    "360 spiral galaxy",
    "361 gas pillars",
    "362 supernova shells",
    "363 milky band",
    "364 ink nebula",
    "365 dark nebula",
    "366 planetary nebula",
    "367 stellar nursery",
    "368 pool caustics",
    "369 sunlit shallows",
    "370 deep water",
    "371 cell caustics",
    "372 water surface",
    "373 rain rings",
    "374 god rays",
    "375 wave interference",
    "376 sand ripples",
    "377 dune field",
    "378 wind streaks",
    "379 raked garden",
    "380 dry lakebed",
    "381 silk folds",
    "382 velvet drape",
    "383 satin ripples",
    "384 corduroy waves",
    "385 flag ripple",
    "386 quilted padding",
    "387 stained glass",
    "388 rose window",
    "389 glass blocks",
    "390 cathedral panes",
    "391 glass shards",
    "392 terrazzo",
    "393 grouted tiles",
    "394 hex mosaic",
    "395 penny tiles",
    "396 byzantine tesserae",
    "397 pebble mosaic",
    "398 broken plates",
    "399 brushed metal",
    "400 spun metal",
    "401 hammered metal",
    "402 anodized sheen",
    "403 damascus steel",
    "404 crushed velvet",
    "405 velvet nap",
    "406 velvet swirl",
    "407 geodesic dome",
    "408 lowpoly terrain",
    "409 soft facets",
    "410 warped mesh",
    "411 delaunay bloom",
    "412 soft sunburst",
    "413 twin sunbursts",
    "414 spiral rays",
    "415 rays through cloud",
    "416 fan blades",
    "417 sun halo",
    "418 breathing rings",
    "419 ring moire",
    "420 elliptic rings",
    "421 rounded squares",
    "422 ripple rings",
    "423 ring tunnel",
    "424 warped grid",
    "425 wavy checker",
    "426 fisheye grid",
    "427 twisted grid",
    "428 soft tartan",
    "429 soft argyle",
    "430 spiral tiedye",
    "431 bullseye tiedye",
    "432 crumple dye",
    "433 shibori stripes",
    "434 mandala dye",
    "435 watercolour blooms",
    "436 wet washes",
    "437 granulation",
    "438 colour field washes",
    "439 ink blotches",
    "440 gouache smudge",
    "441 ink drops",
    "442 suminagashi",
    "443 ink tendrils",
    "444 ink wash gradient",
    "445 alcohol ink",
    "446 agate bands",
    "447 malachite",
    "448 wood grain",
    "449 marble veins",
    "450 onyx layers",
    "451 topo contours",
    "452 terraced hills",
    "453 bathymetry",
    "454 heat contours",
    "455 isobar map",
    "456 lava wall",
    "457 bokeh field",
    "458 foam cells",
    "459 soft kaleido",
    "460 flow streamlines",
    "461 curtain folds",
    "462 soap film",
    "463 julia drift",
    "464 gradient mesh",
    "465 frost feathers",
    "466 light leaks",
    "467 chrome ripples",
    "468 hue clouds",
    "469 forked bolt",
    "470 sheet lightning",
    "471 ball lightning",
    "472 ribbon lightning",
    "473 chain lightning",
    "474 storm front",
    "475 frozen bolt",
    "476 lightning mandala",
    "477 kaleido bolt",
    "478 crawler arcs",
    "479 spider lightning",
    "480 tesla coil",
    "481 plasma globe",
    "482 bolt rain",
    "483 sea lightning",
    "484 lightning ring",
    "485 heat lightning",
    "486 volcanic lightning",
    "487 aurora bolts",
    "488 lichtenberg tree",
    "489 lichtenberg disc",
    "490 electric web",
    "491 jacobs ladder",
    "492 helix bolt",
    "493 lightning lattice",
    "494 upward streamers",
    "495 lightning wheel",
    "496 storm horizon",
    "497 sprite lightning",
    "498 cage lightning",
    "499 arc flash",
    "500 lightning veins",
    "501 st elmos fire",
    "502 thunder cell",
    "503 lightning script",
    "504 chandelier bolts",
    "505 lightning spiral",
    "506 ground strike",
    "507 lightning snowflake",
    "508 cloud to cloud",
    "509 lightning circle",
    "510 lissajous bolt",
    "511 twelvefold mandala",
    "512 ball lightning drift",
    "513 rolling front",
    "514 bead lightning",
    "515 frozen twins",
    "516 skyline leaders",
    "517 horizon crawler",
    "518 sheet wash",
    "519 plasma frame",
    "520 rose bolt",
    "521 star bolt",
    "522 ribbon wave",
    "523 strike cascade",
    "524 orbiting balls",
    "525 anvil underside",
    "526 lightning heart",
    "527 lightning tunnel",
    "528 lightning comet",
    "529 bolt fountain",
    "530 corona disc",
    "531 electric atom",
    "532 stepped leader",
    "533 lightning echo",
    "534 whip bolt",
    "535 electric jellyfish",
    "536 static cloud",
    "537 pylon arcs",
    "538 lightning vortex",
    "539 spark rain",
    "540 cloud rift",
    "541 comet trio",
    "542 satellite orbits",
    "543 drifting polygons",
    "544 nested rings",
    "545 spinning stars",
    "546 floating lanterns",
    "547 slow meteors",
    "548 soap bubbles",
    "549 paper planes",
    "550 kites on strings",
    "551 hummingbirds",
    "552 koi shapes",
    "553 origami cranes",
    "554 spinning tops",
    "555 pendulums",
    "556 gyroscopes",
    "557 gear pair",
    "558 gear train",
    "559 planetary set",
    "560 gear silhouettes",
    "561 edge gear",
    "562 gear cascade",
    "563 corner train",
    "564 gear mandala",
    "565 pinion ladder",
    "566 sprocket chain",
    "567 rolling pinions",
    "568 rack and pinion",
    "569 pendulum wave",
    "570 orrery",
    "571 clockwork pendulum",
    "572 matrix four edges",
    "573 matrix spokes",
    "574 matrix heavy top",
    "575 matrix slow mutation",
    "576 matrix dense field",
    "577 matrix sparse spark",
    "578 matrix side rain",
    "579 matrix pileup",
    "580 matrix rising",
    "581 matrix corners",
    "582 rising embers",
    "583 dust shaft",
    "584 filament web",
    "585 constellation connect",
    "586 fireflies",
    "587 slow snow",
    "588 pollen drift",
    "589 grinder sparks",
    "590 plankton wake",
    "591 star trails",
    "592 twinkle net",
    "593 lantern drift",
    "594 ember column",
    "595 mote swarm",
    "596 frost glints",
    "597 will o wisp",
    "598 rain glints",
    "599 dandelion seeds",
    "600 comet dust",
    "601 glyph glints",
    "602 string envelope",
    "603 emblem ghost",
    "604 mandel deep",
    "605 julia morph",
    "606 burning ship",
    "607 newton basins",
    "608 lyapunov",
    "609 buddhabrot",
    "610 flame ifs",
};
const unsigned char jd_pattern_family[] = {
    3,
    2,
    3,
    2,
    3,
    0,
    3,
    3,
    1,
    2,
    3,
    3,
    1,
    3,
    3,
    3,
    0,
    3,
    4,
    8,
    4,
    0,
    4,
    0,
    5,
    3,
    3,
    0,
    2,
    2,
    1,
    1,
    3,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    3,
    0,
    2,
    1,
    0,
    0,
    3,
    0,
    0,
    5,
    1,
    3,
    3,
    5,
    5,
    3,
    0,
    0,
    4,
    2,
    7,
    3,
    3,
    3,
    3,
    7,
    7,
    7,
    3,
    4,
    0,
    0,
    6,
    0,
    0,
    4,
    0,
    1,
    3,
    0,
    2,
    2,
    3,
    0,
    0,
    0,
    3,
    0,
    3,
    0,
    2,
    3,
    1,
    0,
    0,
    5,
    3,
    0,
    3,
    4,
    4,
    3,
    2,
    3,
    4,
    0,
    0,
    5,
    5,
    0,
    4,
    3,
    1,
    0,
    3,
    2,
    5,
    3,
    1,
    0,
    4,
    8,
    1,
    5,
    0,
    0,
    1,
    1,
    2,
    0,
    4,
    1,
    4,
    0,
    0,
    7,
    0,
    0,
    8,
    0,
    4,
    4,
    8,
    4,
    8,
    4,
    1,
    3,
    5,
    6,
    2,
    1,
    0,
    1,
    8,
    1,
    0,
    4,
    7,
    1,
    0,
    3,
    1,
    4,
    3,
    4,
    4,
    1,
    4,
    4,
    1,
    1,
    1,
    0,
    3,
    3,
    1,
    5,
    1,
    0,
    1,
    1,
    4,
    0,
    4,
    5,
    1,
    0,
    0,
    1,
    1,
    1,
    0,
    3,
    2,
    5,
    0,
    0,
    0,
    0,
    4,
    4,
    0,
    2,
    0,
    0,
    4,
    4,
    0,
    4,
    0,
    0,
    0,
    3,
    0,
    0,
    0,
    0,
    0,
    1,
    4,
    4,
    0,
    0,
    3,
    0,
    0,
    0,
    0,
    0,
    4,
    4,
    4,
    3,
    2,
    1,
    4,
    0,
    7,
    0,
    2,
    3,
    2,
    0,
    0,
    4,
    1,
    0,
    0,
    2,
    0,
    0,
    3,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    1,
    0,
    0,
    2,
    0,
    0,
    0,
    3,
    0,
    4,
    3,
    0,
    3,
    4,
    3,
    4,
    0,
    3,
    0,
    3,
    0,
    0,
    0,
    0,
    4,
    2,
    0,
    0,
    3,
    0,
    4,
    5,
    0,
    0,
    2,
    3,
    0,
    0,
    0,
    1,
    0,
    0,
    1,
    4,
    0,
    0,
    5,
    4,
    0,
    0,
    1,
    3,
    4,
    3,
    3,
    0,
    4,
    1,
    0,
    7,
    0,
    0,
    1,
    0,
    1,
    0,
    3,
    0,
    0,
    2,
    3,
    0,
    0,
    4,
    4,
    1,
    4,
    4,
    4,
    0,
    2,
    0,
    4,
    4,
    4,
    4,
    0,
    4,
    0,
    4,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    3,
    3,
    7,
    0,
    0,
    4,
    0,
    0,
    0,
    4,
    7,
    0,
    4,
    0,
    5,
    0,
    4,
    4,
    0,
    0,
    0,
    0,
    3,
    0,
    4,
    1,
    4,
    2,
    0,
    3,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    0,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    0,
    5,
    2,
    7,
    1,
    3,
    3,
    3,
    0,
    3,
    0,
    0,
    4,
    0,
    0,
    4,
    7,
    2,
    2,
    2,
    2,
    2,
    0,
    3,
    0,
    0,
    0,
    3,
    1,
    0,
    0,
    0,
    4,
    0,
    4,
    0,
    4,
    4,
    4,
    0,
    0,
    5,
    4,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    3,
    4,
    3,
    0,
    8,
    0,
    0,
    0,
    4,
    0,
    6,
    6,
    6,
    6,
    6,
    0,
    6,
    3,
    3,
    0,
    6,
    6,
    4,
    5,
    6,
    6,
    6,
    6,
    4,
    0,
    0,
    1,
    0,
    6,
    2,
    0,
    6,
    0,
    6,
    6,
    0,
    6,
    6,
    0,
    6,
    6,
    3,
    0,
    5,
    0,
    6,
    1,
    3,
    4,
    0,
    6,
    0,
    0,
    0,
    0,
    4,
    3,
    3,
    4,
    0,
    0,
    0,
    6,
    6,
    5,
    6,
    0,
    0,
    0,
    6,
    6,
    0,
    0,
    0,
    4,
    5,
    0,
    5,
    0,
    4,
    0,
    3,
    5,
    5,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    5,
    0,
    0,
    0,
    0,
    5,
    3,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    0,
    3,
    0,
    0,
    0,
    5,
    5,
    0,
    0,
    0,
    5,
    5,
    1,
    0,
    0,
    5,
    4,
    5,
    5,
    3,
    4,
    4,
    5,
    5,
    5,
    0,
    5,
    5,
    5,
    5,
    1,
    0,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
};
const int jd_pattern_count = 610;
