#!/bin/bash
# regenerate patterns_c/registry.c from patterns_c/pattern_*.c
cd "$(dirname "$0")/../patterns_c" || exit 1
{
  echo '/* auto-generated by tools/gen_registry.sh */'
  echo '#include "../jellydazzle.h"'
  for f in $(ls pattern_*.c 2>/dev/null | sort); do
    fn="${f%.c}"
    echo "extern void ${fn}(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);"
  done
  echo 'const jd_pattern_fn jd_patterns[] = {'
  for f in $(ls pattern_*.c 2>/dev/null | sort); do
    echo "    ${f%.c},"
  done
  echo '};'
  n=$(ls pattern_*.c 2>/dev/null | wc -l | tr -d ' ')
  echo "const int jd_pattern_count = ${n};"
} > registry.c
echo "registry: $(ls pattern_*.c 2>/dev/null | wc -l | tr -d ' ') patterns"
