#!/bin/bash
# regenerate src/patterns/_registry.c from src/patterns/NNN_*.c
cd "$(dirname "$0")/../src/patterns" || exit 1
files=$(ls [0-9][0-9][0-9]_*.c [0-9][0-9][0-9].c 2>/dev/null | sort)
{
  echo '/* auto-generated by tools/gen_registry.sh — do not edit */'
  echo '#include "../engine/jellydazzle.h"'
  for f in $files; do
    n="${f:0:3}"
    echo "extern void pattern_${n}(uint32_t*, int, int, int, int, uint32_t, const uint32_t*);"
  done
  echo 'const jd_pattern_fn jd_patterns[] = {'
  for f in $files; do echo "    pattern_${f:0:3},"; done
  echo '};'
  echo "const int jd_pattern_count = $(echo "$files" | wc -w | tr -d ' ');"
} > _registry.c
echo "registry: $(echo "$files" | wc -w | tr -d ' ') patterns"
